### PR TITLE
new contributing rules added

### PR DESCRIPTION
**Pull request by vbindal**
I have added some contributing rules with procedure please take a look

### CODE REVIEW

**Comment by Anudeep-313** [comment]
this file has some conflicts, please try creating a new PR for this again.  i will close the present PR now.

**Comment by vbindal** [comment]
please allow me to create a new PR i am unable to push the changes for the same 
I am getting this  error :
remote: Permission to Anudeep-313/mini-project.git denied to vbindal.
fatal: unable to access 'https://github.com/Anudeep-313/mini-project.git/': The requested URL returned error: 403

**Comment by Anudeep-313** [comment]
create a new PR!!. Are you not able to create new PR ??

**Comment by vbindal** [comment]
No sir i am getting error while pushing changes in new branch

**Comment by Anudeep-313** [comment]
try now!!

**Comment by vbindal** [comment]
okay

**Pull request merged**
